### ISSUE TITLE
Need help! How to pass the serializers with the QuerySetSequence?

### ISSUE THREAD

**Issue by c0d33py** [clokep/django-querysetsequence#105]
In my Django project, I have a `FeedSerializer` that contains two nested serializers `(ArticleSerializer and SubjectSerializer)`. The goal is to use `QuerySetSequence` in the `FeedListApiView` in views.py to combine data from multiple models `(Article and Ticker)` and pass it to the `FeedSerializer`.

Here's my code:

serializers.py

```py

class FeedSerializer(serializers.Serializer):
    article = ArticleSerializer(many=True, read_only=True)
    subject = SubjectSerializer(many=True, read_only=True)

    class Meta:
        fields = '__all__'
```

views.py
```py
class FeedListApiView(ModelViewSet):
    """
    Feed list API View.
    """

    serializer_class = FeedSerializer
    pagination_class = FeedPagination

    def get_queryset(self):
        query = QuerySetSequence(
            Article.objects.all(),
            Ticker.objects.all(),
        )

        return query

```

**Comment by clokep** [comment]
That looks vaguely right according to the [documentation](https://django-querysetsequence.readthedocs.io/en/latest/example.html) -- are you hitting an error or something?

**Comment by clokep** [comment]
Closing due to lack of response.
